apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nodejs-demo
  name: nodejs-demo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodejs-demo
    spec:
      containers:
      - image: sathishlxg/nodejs-demo
        name: nodejs-demo
        ports:
        - name: nodejs-demo
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nodejs-demo
  name: nodejs-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: nodejs-demo